language: python
python: 2.7
env:
    - TOXENV=py26-normal
    - TOXENV=py27-normal
    - TOXENV=pypy-normal
    - TOXENV=py33-normal
    - TOXENV=py34-normal
    - TOXENV=py35-normal
    - TOXENV=py26-uwsgi
    - TOXENV=py27-uwsgi
    - TOXENV=py33-uwsgi
    - TOXENV=py34-uwsgi
    - TOXENV=py35-uwsgi

install:
    # Travis uses an outdated PyPy, this installs the most recent one.
    # This makes the tests run on Travis' legacy infrastructure, but so be it.
    # temporary pyenv installation to get pypy-2.6 before container infra upgrade
    - if [ "$TOXENV" == "pypy" ]; then
        git clone https://github.com/yyuu/pyenv.git ~/.pyenv;
        PYENV_ROOT="$HOME/.pyenv";
        PATH="$PYENV_ROOT/bin:$PATH";
        eval "$(pyenv init -)";
        pyenv install pypy-2.6.1;
        pyenv global pypy-2.6.1;
      fi
    - python --version
    - pip install tox flake8

script:
    - tox
    - make stylecheck

branches:
  except:
    - website

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
