language: python
#python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
# command to install dependencies
install:
  - pip install -r .test-requirements.txt
env:
  - TOX_ENV=py27
  - TOX_ENV=py26
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pep8
  - TOX_ENV=isort
  - TOX_ENV=flake8
  - TOX_ENV=flake8-complexity
  - TOX_ENV=docs
  - TOX_ENV=testcoverage

script:
  - tox -e $TOX_ENV
